export type FieldDef = { label: string; key: string; rows?: number }

export const STUDY_FIELDS: Record<string, FieldDef[]> = {
  "USG Abdomen": [
    { label: "LIVER", key: "liver", rows: 3 },
    { label: "GALL BLADDER", key: "gallBladder", rows: 2 },
    { label: "COMMON BILE DUCT", key: "cbd", rows: 1 },
    { label: "PANCREAS", key: "pancreas", rows: 2 },
    { label: "SPLEEN", key: "spleen", rows: 2 },
    { label: "RIGHT KIDNEY", key: "rightKidney", rows: 2 },
    { label: "LEFT KIDNEY", key: "leftKidney", rows: 2 },
    { label: "URINARY BLADDER", key: "bladder", rows: 2 },
  ],
  "USG Pelvis": [
    { label: "UTERUS", key: "uterus", rows: 3 },
    { label: "ENDOMETRIUM", key: "endometrium", rows: 2 },
    { label: "RIGHT OVARY", key: "rightOvary", rows: 2 },
    { label: "LEFT OVARY", key: "leftOvary", rows: 2 },
    { label: "URINARY BLADDER", key: "bladder", rows: 2 },
    { label: "FREE FLUID", key: "freeFluid", rows: 1 },
  ],
  "USG Abdomen & Pelvis": [
    { label: "LIVER", key: "liver", rows: 3 },
    { label: "GALL BLADDER", key: "gallBladder", rows: 2 },
    { label: "COMMON BILE DUCT", key: "cbd", rows: 1 },
    { label: "PANCREAS", key: "pancreas", rows: 2 },
    { label: "SPLEEN", key: "spleen", rows: 2 },
    { label: "RIGHT KIDNEY", key: "rightKidney", rows: 2 },
    { label: "LEFT KIDNEY", key: "leftKidney", rows: 2 },
    { label: "UTERUS", key: "uterus", rows: 2 },
    { label: "BOTH OVARIES", key: "ovaries", rows: 2 },
    { label: "URINARY BLADDER", key: "bladder", rows: 2 },
  ],
  "USG Kidney (KUB)": [
    { label: "RIGHT KIDNEY", key: "rightKidney", rows: 3 },
    { label: "LEFT KIDNEY", key: "leftKidney", rows: 3 },
    { label: "URINARY BLADDER", key: "bladder", rows: 2 },
  ],
  "USG Thyroid & Neck": [
    { label: "RIGHT LOBE OF THYROID", key: "rightThyroid", rows: 3 },
    { label: "LEFT LOBE OF THYROID", key: "leftThyroid", rows: 3 },
    { label: "ISTHMUS", key: "isthmus", rows: 2 },
    { label: "NECK", key: "neck", rows: 2 },
  ],
  "USG Breast (Both)": [
    { label: "RIGHT BREAST", key: "rightBreast", rows: 3 },
    { label: "LEFT BREAST", key: "leftBreast", rows: 3 },
    { label: "BOTH AXILLAE", key: "axillae", rows: 2 },
  ],
  "Doppler Study": [{ label: "FINDINGS", key: "findings", rows: 5 }],
  "USG Upper Abdomen": [
    { label: "LIVER", key: "liver", rows: 3 },
    { label: "GALL BLADDER", key: "gallBladder", rows: 2 },
    { label: "COMMON BILE DUCT", key: "cbd", rows: 1 },
    { label: "PANCREAS", key: "pancreas", rows: 2 },
    { label: "SPLEEN", key: "spleen", rows: 2 },
    { label: "KIDNEYS", key: "kidneys", rows: 2 },
  ],
  "USG Scrotum": [
    { label: "RIGHT TESTIS", key: "rightTestis", rows: 3 },
    { label: "LEFT TESTIS", key: "leftTestis", rows: 3 },
    { label: "DOPPLER EXAMINATION", key: "doppler", rows: 2 },
  ],
  "USG Chest": [
    { label: "PLEURAL SPACES", key: "pleural", rows: 2 },
    { label: "FINDINGS", key: "findings", rows: 3 },
  ],
  "USG Axilla": [{ label: "FINDINGS", key: "findings", rows: 3 }],
  "USG Bladder & Prostate": [
    { label: "URINARY BLADDER", key: "bladder", rows: 2 },
    { label: "PROSTATE", key: "prostate", rows: 3 },
  ],
  "USG Inguinal Region": [{ label: "FINDINGS", key: "findings", rows: 4 }],
  "USG Parotid Gland": [
    { label: "RIGHT PAROTID", key: "rightParotid", rows: 2 },
    { label: "LEFT PAROTID", key: "leftParotid", rows: 2 },
    { label: "LYMPH NODES", key: "lymphNodes", rows: 2 },
  ],
  "USG Local Part": [{ label: "FINDINGS", key: "findings", rows: 5 }],
  "Follicular Study": [
    { label: "LMP", key: "lmp", rows: 1 },
    { label: "FOLLICULAR MONITORING (Date | Day | RT Follicle | LT Follicle | Endometrium | Free Fluid)", key: "monitoring", rows: 6 },
  ],
  "Carotid Doppler": [
    { label: "COMMON CAROTID ARTERY", key: "cca", rows: 2 },
    { label: "INTERNAL CAROTID ARTERY", key: "ica", rows: 2 },
    { label: "EXTERNAL CAROTID ARTERY", key: "eca", rows: 1 },
    { label: "VERTEBRAL ARTERY", key: "vertebral", rows: 1 },
  ],
  "Portal Vein Doppler": [
    { label: "PORTAL VEIN", key: "portalVein", rows: 2 },
    { label: "HEPATIC VEINS", key: "hepaticVeins", rows: 2 },
    { label: "SPLENIC VEIN", key: "splenicVein", rows: 1 },
  ],
  "Renal Artery Doppler": [
    { label: "GRAY SCALE EXAMINATION", key: "grayScale", rows: 3 },
    { label: "RIGHT RENAL ARTERY", key: "rightRenal", rows: 2 },
    { label: "LEFT RENAL ARTERY", key: "leftRenal", rows: 2 },
  ],
  "Lower Limb Venous Doppler": [
    { label: "RIGHT LOWER LIMB – DEEP VEINS", key: "rightDeepVeins", rows: 3 },
    { label: "LEFT LOWER LIMB – DEEP VEINS", key: "leftDeepVeins", rows: 3 },
  ],
  "Lower Limb Arterial Doppler": [
    { label: "RIGHT LOWER LIMB ARTERIES", key: "rightArterial", rows: 4 },
    { label: "LEFT LOWER LIMB ARTERIES", key: "leftArterial", rows: 4 },
  ],
  "Upper Limb Doppler": [
    { label: "RIGHT UPPER LIMB", key: "rightUL", rows: 4 },
    { label: "LEFT UPPER LIMB", key: "leftUL", rows: 4 },
  ],
  "Obstetric USG (1st Trimester)": [
    { label: "UTERUS", key: "uterus", rows: 2 },
    { label: "GESTATIONAL SAC", key: "gestationalSac", rows: 2 },
    { label: "EMBRYO / FETUS", key: "embryo", rows: 2 },
    { label: "YOLK SAC", key: "yolkSac", rows: 1 },
    { label: "CARDIAC ACTIVITY", key: "cardiac", rows: 1 },
  ],
  "Obstetric USG (2nd / 3rd Trim.)": [
    { label: "FETAL PRESENTATION", key: "presentation", rows: 1 },
    { label: "BIOMETRY (BPD / HC / AC / FL)", key: "biometry", rows: 2 },
    { label: "FETAL HEART RATE", key: "fhr", rows: 1 },
    { label: "FETAL WEIGHT", key: "fetalWeight", rows: 1 },
    { label: "PLACENTA", key: "placenta", rows: 2 },
    { label: "LIQUOR (AFI)", key: "liquor", rows: 1 },
    { label: "CERVIX", key: "cervix", rows: 1 },
  ],
  "Fetal Well-Being Profile": [
    { label: "FETAL PRESENTATION", key: "presentation", rows: 1 },
    { label: "FHR & RHYTHM", key: "fhr", rows: 1 },
    { label: "FETAL MOVEMENTS", key: "movements", rows: 1 },
    { label: "FETAL TONE", key: "tone", rows: 1 },
    { label: "LIQUOR (AFI)", key: "liquor", rows: 1 },
    { label: "BIOPHYSICAL SCORE", key: "bps", rows: 1 },
    { label: "PLACENTA", key: "placenta", rows: 2 },
  ],
  "Trans-Vaginal Sonography (TVS)": [
    { label: "UTERUS", key: "uterus", rows: 3 },
    { label: "ENDOMETRIUM", key: "endometrium", rows: 2 },
    { label: "RIGHT OVARY", key: "rightOvary", rows: 2 },
    { label: "LEFT OVARY", key: "leftOvary", rows: 2 },
    { label: "POUCH OF DOUGLAS", key: "pod", rows: 2 },
  ],
  "USG Guided FNAC": [
    { label: "LESION DETAILS", key: "lesion", rows: 3 },
    { label: "PROCEDURE", key: "procedure", rows: 2 },
    { label: "CYTOLOGY", key: "cytology", rows: 3 },
  ],
  "X-Ray Chest PA": [{ label: "FINDINGS", key: "findings", rows: 4 }],
  "X-Ray Chest AP + LAT": [{ label: "FINDINGS", key: "findings", rows: 4 }],
  "X-Ray LS Spine AP + LAT": [
    { label: "VERTEBRAL BODIES", key: "vertebrae", rows: 2 },
    { label: "INTERVERTEBRAL DISCS", key: "discs", rows: 2 },
    { label: "FINDINGS", key: "findings", rows: 2 },
  ],
  "X-Ray Cervical Spine": [
    { label: "VERTEBRAL BODIES", key: "vertebrae", rows: 2 },
    { label: "INTERVERTEBRAL DISCS", key: "discs", rows: 2 },
    { label: "FINDINGS", key: "findings", rows: 2 },
  ],
  "X-Ray Skull AP + LAT": [{ label: "FINDINGS", key: "findings", rows: 4 }],
  "X-Ray KUB": [{ label: "FINDINGS", key: "findings", rows: 4 }],
  "X-Ray Knee AP + LAT": [
    { label: "JOINT SPACE", key: "jointSpace", rows: 2 },
    { label: "BONY STRUCTURES", key: "bones", rows: 2 },
    { label: "FINDINGS", key: "findings", rows: 2 },
  ],
  "X-Ray Hip Joint": [
    { label: "JOINT SPACE", key: "jointSpace", rows: 2 },
    { label: "BONY STRUCTURES", key: "bones", rows: 2 },
    { label: "FINDINGS", key: "findings", rows: 2 },
  ],
  "X-Ray Shoulder": [{ label: "FINDINGS", key: "findings", rows: 4 }],
  "X-Ray Hand / Wrist": [{ label: "FINDINGS", key: "findings", rows: 4 }],
  "X-Ray Foot / Ankle": [{ label: "FINDINGS", key: "findings", rows: 4 }],
  "X-Ray PNS / Sinus": [{ label: "FINDINGS", key: "findings", rows: 4 }],
  "X-Ray Dorsal Spine": [
    { label: "VERTEBRAL BODIES", key: "vertebrae", rows: 2 },
    { label: "INTERVERTEBRAL DISCS", key: "discs", rows: 2 },
    { label: "FINDINGS", key: "findings", rows: 2 },
  ],
  "X-Ray Elbow":           [{ label: "FINDINGS", key: "findings", rows: 4 }],
  "X-Ray Forearm":         [{ label: "FINDINGS", key: "findings", rows: 4 }],
  "X-Ray Leg":             [{ label: "FINDINGS", key: "findings", rows: 4 }],
  "X-Ray Mandible":        [{ label: "FINDINGS", key: "findings", rows: 3 }],
  "X-Ray Mastoid":         [{ label: "FINDINGS", key: "findings", rows: 3 }],
  "X-Ray Nasal Bones":     [{ label: "FINDINGS", key: "findings", rows: 3 }],
  "X-Ray Calcaneum":       [{ label: "FINDINGS", key: "findings", rows: 3 }],
  "X-Ray Abdomen (Erect)": [{ label: "FINDINGS", key: "findings", rows: 4 }],
  "MRI Brain (Plain)": [
    { label: "BRAIN PARENCHYMA", key: "parenchyma", rows: 3 },
    { label: "VENTRICLES", key: "ventricles", rows: 2 },
    { label: "CEREBELLUM & BRAINSTEM", key: "cerebellum", rows: 2 },
    { label: "WHITE MATTER", key: "whiteMatter", rows: 2 },
    { label: "VASCULAR STRUCTURES", key: "vascular", rows: 2 },
  ],
  "MRI Brain with Contrast": [
    { label: "BRAIN PARENCHYMA", key: "parenchyma", rows: 3 },
    { label: "VENTRICLES", key: "ventricles", rows: 2 },
    { label: "CEREBELLUM & BRAINSTEM", key: "cerebellum", rows: 2 },
    { label: "WHITE MATTER", key: "whiteMatter", rows: 2 },
    { label: "POST CONTRAST ENHANCEMENT", key: "enhancement", rows: 2 },
    { label: "VASCULAR STRUCTURES", key: "vascular", rows: 2 },
  ],
  "MRI Spine – Cervical": [
    { label: "VERTEBRAL BODIES", key: "vertebrae", rows: 2 },
    { label: "INTERVERTEBRAL DISCS", key: "discs", rows: 3 },
    { label: "SPINAL CANAL", key: "canal", rows: 2 },
    { label: "CORD SIGNAL", key: "cord", rows: 2 },
    { label: "PARASPINAL MUSCLES", key: "paraspinal", rows: 1 },
  ],
  "MRI Spine – Lumbar": [
    { label: "VERTEBRAL BODIES", key: "vertebrae", rows: 2 },
    { label: "INTERVERTEBRAL DISCS", key: "discs", rows: 3 },
    { label: "SPINAL CANAL", key: "canal", rows: 2 },
    { label: "CONUS MEDULLARIS", key: "conus", rows: 1 },
    { label: "PARASPINAL MUSCLES", key: "paraspinal", rows: 1 },
  ],
  "MRI Knee": [
    { label: "BONY STRUCTURES", key: "bones", rows: 2 },
    { label: "ARTICULAR CARTILAGE", key: "cartilage", rows: 2 },
    { label: "MENISCI", key: "menisci", rows: 2 },
    { label: "LIGAMENTS (ACL / PCL / MCL / LCL)", key: "ligaments", rows: 2 },
    { label: "JOINT SPACE & EFFUSION", key: "jointSpace", rows: 1 },
  ],
  "MRI Shoulder": [
    { label: "ROTATOR CUFF", key: "rotatorCuff", rows: 3 },
    { label: "ACROMIOCLAVICULAR JOINT", key: "acJoint", rows: 1 },
    { label: "GLENOHUMERAL JOINT", key: "ghJoint", rows: 2 },
    { label: "LABRUM", key: "labrum", rows: 2 },
    { label: "SOFT TISSUES", key: "softTissues", rows: 1 },
  ],
  "MRI Abdomen": [
    { label: "LIVER", key: "liver", rows: 2 },
    { label: "SPLEEN", key: "spleen", rows: 1 },
    { label: "PANCREAS", key: "pancreas", rows: 2 },
    { label: "KIDNEYS", key: "kidneys", rows: 2 },
    { label: "ADRENALS", key: "adrenals", rows: 1 },
    { label: "OTHER STRUCTURES", key: "others", rows: 2 },
  ],
  "MRI Pelvis": [
    { label: "UTERUS / PROSTATE", key: "uterusProstate", rows: 3 },
    { label: "URINARY BLADDER", key: "bladder", rows: 2 },
    { label: "RECTUM & SIGMOID", key: "rectum", rows: 2 },
    { label: "LYMPH NODES", key: "lymphNodes", rows: 1 },
    { label: "PELVIC FLOOR", key: "pelvicFloor", rows: 1 },
  ],
  "MRA Brain": [{ label: "FINDINGS", key: "findings", rows: 5 }],
  "CT Brain (Plain)": [
    { label: "BRAIN PARENCHYMA", key: "parenchyma", rows: 3 },
    { label: "VENTRICLES", key: "ventricles", rows: 2 },
    { label: "EXTRA-AXIAL SPACES", key: "extraAxial", rows: 2 },
    { label: "BONY STRUCTURES", key: "bones", rows: 1 },
  ],
  "CT Brain with Contrast": [
    { label: "BRAIN PARENCHYMA", key: "parenchyma", rows: 3 },
    { label: "VENTRICLES", key: "ventricles", rows: 2 },
    { label: "EXTRA-AXIAL SPACES", key: "extraAxial", rows: 2 },
    { label: "POST CONTRAST ENHANCEMENT", key: "enhancement", rows: 2 },
  ],
  "CT Chest (HRCT)": [
    { label: "LUNG PARENCHYMA", key: "lungs", rows: 4 },
    { label: "PLEURA", key: "pleura", rows: 2 },
    { label: "MEDIASTINUM", key: "mediastinum", rows: 2 },
    { label: "BONY THORAX", key: "bones", rows: 1 },
  ],
  "CT Abdomen (Plain)": [
    { label: "LIVER", key: "liver", rows: 2 },
    { label: "SPLEEN", key: "spleen", rows: 1 },
    { label: "PANCREAS", key: "pancreas", rows: 2 },
    { label: "KIDNEYS", key: "kidneys", rows: 2 },
    { label: "BOWEL", key: "bowel", rows: 2 },
    { label: "OTHER STRUCTURES", key: "others", rows: 1 },
  ],
  "CT Abdomen + Pelvis": [
    { label: "LIVER", key: "liver", rows: 2 },
    { label: "SPLEEN", key: "spleen", rows: 1 },
    { label: "PANCREAS", key: "pancreas", rows: 2 },
    { label: "KIDNEYS", key: "kidneys", rows: 2 },
    { label: "PELVIC ORGANS", key: "pelvis", rows: 2 },
    { label: "LYMPH NODES", key: "lymphNodes", rows: 1 },
  ],
  "CT KUB (Urography)": [
    { label: "KIDNEYS", key: "kidneys", rows: 3 },
    { label: "URETERS", key: "ureters", rows: 2 },
    { label: "URINARY BLADDER", key: "bladder", rows: 2 },
    { label: "CALCULI", key: "calculi", rows: 2 },
  ],
  "CT Spine – Lumbar": [
    { label: "VERTEBRAL BODIES", key: "vertebrae", rows: 2 },
    { label: "INTERVERTEBRAL DISCS", key: "discs", rows: 3 },
    { label: "SPINAL CANAL", key: "canal", rows: 2 },
    { label: "NEURAL FORAMINA", key: "foramina", rows: 1 },
  ],
  "CT Angiography": [{ label: "FINDINGS", key: "findings", rows: 5 }],
  "Complete Blood Count (CBC)": [{ label: "RESULTS / VALUES", key: "results", rows: 5 }],
  "Blood Sugar – Fasting": [{ label: "RESULTS / VALUES", key: "results", rows: 3 }],
  "Blood Sugar – PP": [{ label: "RESULTS / VALUES", key: "results", rows: 3 }],
  "HbA1c": [{ label: "RESULTS / VALUES", key: "results", rows: 3 }],
  "Thyroid Profile (T3, T4, TSH)": [{ label: "RESULTS / VALUES", key: "results", rows: 4 }],
  "Liver Function Test (LFT)": [{ label: "RESULTS / VALUES", key: "results", rows: 5 }],
  "Kidney Function Test (KFT)": [{ label: "RESULTS / VALUES", key: "results", rows: 4 }],
  "Lipid Profile": [{ label: "RESULTS / VALUES", key: "results", rows: 5 }],
  "Urine Routine": [{ label: "RESULTS / VALUES", key: "results", rows: 4 }],
  "Serum Creatinine": [{ label: "RESULTS / VALUES", key: "results", rows: 3 }],
  "Widal Test": [{ label: "RESULTS / VALUES", key: "results", rows: 3 }],
  "Dengue NS1 Ag": [{ label: "RESULTS / VALUES", key: "results", rows: 3 }],
  "ECG (12 Lead)": [
    { label: "RATE & RHYTHM", key: "rhythm", rows: 1 },
    { label: "FINDINGS", key: "findings", rows: 3 },
  ],
  "Echocardiography (ECHO)": [
    { label: "LV FUNCTION (EF%)", key: "lv", rows: 2 },
    { label: "VALVES", key: "valves", rows: 3 },
    { label: "OTHER FINDINGS", key: "findings", rows: 2 },
  ],
  "Stress Test (TMT)": [
    { label: "BASELINE ECG", key: "baseline", rows: 2 },
    { label: "STRESS FINDINGS", key: "findings", rows: 3 },
  ],
  "Holter Monitor (24hr)": [
    { label: "RHYTHM ANALYSIS", key: "rhythm", rows: 3 },
    { label: "FINDINGS", key: "findings", rows: 3 },
  ],
}

export const CATEGORY_FALLBACK: Record<string, FieldDef[]> = {
  Sonography: [{ label: "FINDINGS", key: "findings", rows: 4 }],
  "X-Ray":    [{ label: "FINDINGS", key: "findings", rows: 4 }],
  MRI:        [{ label: "FINDINGS", key: "findings", rows: 5 }],
  "CT Scan":  [{ label: "FINDINGS", key: "findings", rows: 5 }],
  Pathology:  [{ label: "RESULTS / VALUES", key: "results", rows: 5 }],
  Cardiology: [{ label: "FINDINGS", key: "findings", rows: 4 }],
}

export function getCategory(_studyName: string): string {
  return ""
}

export function getReportFields(studyName: string): FieldDef[] {
  if (STUDY_FIELDS[studyName]) return STUDY_FIELDS[studyName]
  const cat = getCategory(studyName)
  return CATEGORY_FALLBACK[cat] || [{ label: "FINDINGS", key: "findings", rows: 5 }]
}
